/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexionDB.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class BuscarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PlantillaUsuarios
     */
    public BuscarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtUsuario = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jtCargo = new javax.swing.JTextField();
        jtContrasena = new javax.swing.JPasswordField();
        jUsuario = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jCorreo = new javax.swing.JLabel();
        jCargo = new javax.swing.JLabel();
        jContrasena = new javax.swing.JLabel();
        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jBuscado = new javax.swing.JLabel();
        jtBuscado = new javax.swing.JTextField();
        jBusca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtUsuario.setEnabled(false);

        jtNombre.setEnabled(false);

        jtCorreo.setEnabled(false);

        jtCargo.setEnabled(false);

        jtContrasena.setEnabled(false);

        jUsuario.setText("Usuario");

        jNombre.setText("Nombre");

        jCorreo.setText("Correo");

        jCargo.setText("Cargo");

        jContrasena.setText("Contraseña");

        jAceptar.setText("Editar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });

        jCancelar.setText("Salir");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        jBuscado.setText("Buscar Usuario:");

        jBusca.setText("Buscar");
        jBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAceptar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNombre)
                                    .addComponent(jCorreo)
                                    .addComponent(jCargo)
                                    .addComponent(jContrasena)
                                    .addComponent(jUsuario))
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jBuscado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtUsuario)
                        .addComponent(jtNombre)
                        .addComponent(jtCorreo)
                        .addComponent(jtCargo)
                        .addComponent(jtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jCancelar))
                    .addComponent(jtBuscado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscado)
                    .addComponent(jtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCorreo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCargo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContrasena))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAceptar)
                    .addComponent(jCancelar)
                    .addComponent(jBusca))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscaActionPerformed
        if (jtBuscado.getText() != "" ){
            jtCargo.enable(true);
            jtContrasena.enable(true);
            jtCorreo.enable(true);
            jtNombre.enable(true);
            jtUsuario.enable(true);
        }
        Conexion consulta = new Conexion();
        try {
            Statement busca = consulta.connection.createStatement();
            ResultSet resultado = busca.executeQuery("SELECT * FROM `usuario` WHERE `uUsuario` LIKE '" + jtBuscado.getText() + "';");
            while (resultado.next()){
                jtNombre.setText( resultado.getString("uNombre") );
                jtCargo.setText( resultado.getString("uCargo") );
                jtUsuario.setText( resultado.getString("uUsuario") );
                jtContrasena.setText( resultado.getString("uContraseña") );
                jtCorreo.setText( resultado.getString("uCorreoElectrónico") );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado");
        }
    }//GEN-LAST:event_jBuscaActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        String usuario = jtUsuario.getText().trim();
        String nombre = jtNombre.getText().trim();
        String correo = jtCorreo.getText().trim();
        String cargo = jtCargo.getText().trim();
        String contrasena = jtContrasena.getText();
        if(usuario.equals("") || nombre.equals("") || correo.equals("") || cargo.equals("") || contrasena.equals("") ){
            JOptionPane.showMessageDialog(null, "Campos vacios");
            return;
        }
        String sql = "UPDATE `usuario` SET `uNombre`= ? , `uCargo`= ? , `uUsuario`= ? , `uContraseña`= ? , `uCorreoElectrónico`= ?  WHERE `uUsuario`='" + jtBuscado.getText() + "'";
        Conexion consulta = new Conexion();
        try {
            PreparedStatement pst = consulta.connection.prepareStatement(sql);
            pst.setString(1, nombre);
            pst.setString(2, cargo);
            pst.setString(3, usuario);
            pst.setString(4, contrasena);
            pst.setString(5, correo);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Modificado con exito");
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(NuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se pudo modificar");
        }
    }//GEN-LAST:event_jAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jBusca;
    private javax.swing.JLabel jBuscado;
    private javax.swing.JButton jCancelar;
    private javax.swing.JLabel jCargo;
    private javax.swing.JLabel jContrasena;
    private javax.swing.JLabel jCorreo;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JTextField jtBuscado;
    private javax.swing.JTextField jtCargo;
    private javax.swing.JPasswordField jtContrasena;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
